### ISSUE TITLE
TIL -2025-05-21  [도커파일을 활용한 배포 방법]

### ISSUE THREAD

**Issue by soheeGit** [soheeGit/Programmers_AI_BackEnd#72]
### 1. 로컬에서 직접 실행 (개발/테스트용)
도커 파일로 이미지를 만든 후, 로컬 환경에서 직접 실행.
```bash
# 1. Dockerfile을 기준으로 이미지 생성
docker build -t my-app .

# 2. 컨테이너 실행
docker run -d -p 8080:80 --name my-app-container my-app
```
- 빠르게 테스트 가능
- CI/CD 없이 수동 배포
- 운영 환경엔 적합하지 않음

### 2. Docker Hub / GHCR / ACR 등에 이미지 푸시 후 실행
이미지를 퍼블릭/프라이빗 레지스트리에 올리고, 다른 서버에서 pull 해서 실행.
```bash
# 1. 빌드
docker build -t my-app .

# 2. 태깅
docker tag my-app docker.io/yourid/my-app:latest

# 3. 푸시
docker push docker.io/yourid/my-app:latest

# 4. 다른 서버에서 pull & run
docker pull docker.io/yourid/my-app:latest
docker run -d -p 8080:80 yourid/my-app:latest
```
- 서버 간 이미지 배포가 쉬움
- CI/CD와 연계 가능

### 3. CI/CD + Docker 배포 (GitHub Actions / Jenkins 등)
CI 도구가 Dockerfile을 빌드하고, 배포 서버에 자동으로 푸시/실행.
예시 (GitHub Actions + EC2):
- GitHub Actions로 Docker 이미지 빌드 → GHCR 업로드
- EC2에 Jenkins 또는 SSH로 접속해 GHCR에서 pull → 실행

```yml
# GitHub Actions 예시
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build -t ghcr.io/yourid/my-app:latest .
      - run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u yourid --password-stdin
      - run: docker push ghcr.io/yourid/my-app:latest
```
- 자동화된 배포 가능
- 프로덕션 환경에 적합
- Nginx + HTTPS 연동도 가능

---

## 📌 오늘의 학습
⭐ 주요 학습내용1

---

## ❗️ Docker 컨테이너화 배포실습 중 오류
```Dockerfile
# Stage 1: Build
FROM eclipse-temurin:17-jdk-alpine AS build
WORKDIR /app

# 그래들 파일 복사 및 의존성 캐싱
COPY gradlew .
COPY gradle gradle
COPY build.gradle settings.gradle ./
RUN chmod +x ./gradlew

# 소스 코드 복사 및 빌드
COPY src src
RUN ./gradlew build -x test

# Stage 2: Runtime
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app

# 빌드 스테이지에서 JAR 파일만 복사
COPY --from=build /app/build/libs/*.jar app.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
```
```bash
docker build -t boot-container:v1 .
```
<img width="1380" alt="Image" src="https://github.com/user-attachments/assets/56d1e7e7-f326-4187-bb73-87051557c863" />
- eclipse-temurin:17-jdk-alpine 이미지를 불러올 수 없음

### 원인
- eclipse-temurin:17-jdk-alpine 이미지는 **현재 사용 중인 플랫폼(rancher-desktop, M2 칩)** 에 맞는 이미지가 Docker Hub에 존재하지 않기 때문이다.
- 특히 alpine 기반의 일부 Java 이미지들은 ARM64 (Apple Silicon) 플랫폼을 지원하지 않는 경우가 많다.

```bash
docker build -t boot-container:v1 . # 이전 명령어
docker build --platform linux/amd64 -t boot-container:v1 . # 플랫폼 관련 이슈 해결
```
- 플랫폼 관련 이슈는 해결했지만, 무한 빌드 에러 발생

### 해결방법
- Dockerfile 변경
```yml
# Stage 1: Build
FROM azul/zulu-openjdk:17-latest AS build
WORKDIR /app

# 그래들 파일 복사 및 의존성 캐싱
COPY gradlew .
COPY gradle gradle
COPY build.gradle settings.gradle ./
RUN chmod +x ./gradlew

# 소스 코드 복사 및 빌드
COPY src src
RUN ./gradlew build -x test

# Stage 2: Runtime
FROM azul/zulu-openjdk:17-latest
WORKDIR /app

# 빌드 스테이지에서 JAR 파일만 복사
COPY --from=build /app/build/libs/*.jar app.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
```
```bash
docker build -t boot-container:v1-arm -f ./Dockerfile-mac .
docker run -d -p 9898:8080 --name boot-container boot-container:v1-arm
```

<img width="942" alt="Image" src="https://github.com/user-attachments/assets/37d99c96-7495-43cf-a54b-8981632d7ec9" />
