### ISSUE TITLE
TIL -2025-05-22  [PostgreSQL + Spring Boot: 개발·배포·Docker Compose 통합]

### ISSUE THREAD

**Issue by soheeGit** [soheeGit/Programmers_AI_BackEnd#73]
## 📌 PostgreSQL + Spring Boot: 개발·배포·Docker Compose 통합
https://hub.docker.com/_/postgres
### 1. PostgreSQL Docker 컨테이너 실행
```bash
docker run -d -p 5432:5432 --name postgres -e POSTGRES_PASSWORD=rootpass postgres:16-alpine 
docker logs postgres
docker ps
```
- 컨테이너 이름: postgres
- 비밀번호: rootpass
- 포트 매핑: 5432:5432

<img width="500" alt="Image" src="https://github.com/user-attachments/assets/2086e099-bbf2-4fb5-ad14-0023dbcf7c1c" />

<img width="300" alt="Image" src="https://github.com/user-attachments/assets/3e86f6ea-a1e3-49b6-b3e2-30736d880e8b" />

<img width="400" alt="Image" src="https://github.com/user-attachments/assets/b259c7a3-606b-4723-befc-1ea886ee0435" />

### 2. 개발 환경 (application-dev.yml)
```yaml
server:
  port: 8080 # 충돌 문제 시 수정
spring:
  # JPA
  jpa:
    hibernate:
      ddl-auto: create 
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect # PostgreSQL
        show_sql: true
        format_sql: true
  # 데이터소스
  datasource:
    driver-class-name: org.postgresql.Driver # PostgreSQL
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: rootpass
```
- localhost를 통해 로컬에서 PostgreSQL 컨테이너에 직접 연결

### 3. 개발 실행 결과
- Pet 엔티티에 대응되는 테이블이 자동 생성됨 (Hibernate ddl-auto: create)
- Docker PostgreSQL과 연결 성공 시 아래처럼 테이블이 보임

<img width="434" alt="Image" src="https://github.com/user-attachments/assets/d1776247-6b4f-43f9-9670-893f46e907ff" />

<img width="900" src="https://github.com/user-attachments/assets/64461035-a23d-495f-8962-f68ae58010bd" />

### 4. 배포 환경 준비 (prod)
- 네트워크 구성
```bash
docker network create db-network
docker network connect db-network postgres
docker network inspect db-network
```
Spring Boot 컨테이너와 PostgreSQL 컨테이너를 같은 네트워크에 연결
내부 통신 주소는 postgres (컨테이너 이름)

- application-prod.yml
```yaml
server:
  port: 8080 # 충돌 문제 시 수정
spring:
  # JPA
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect 
        show_sql: true
        format_sql: true
  # 데이터소스
  datasource:
    driver-class-name: org.postgresql.Driver 
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
```
- .env 파일
```dotenv
DB_URL=jdbc:postgresql://postgres:5432/postgres
DB_USERNAME=postgres
DB_PASSWORD=rootpass
```
PostgreSQL 컨테이너 이름을 postgres로 사용하여 같은 네트워크 내에서 연결

### 5. 배포용 Spring Boot 이미지 빌드 & 실행
```bash
docker build -t my-boot:postgres -f Dockerfile .
docker run -d -p 8787:8080 --name boot-container-250522 --env-file .env --network db-network my-boot:postgres
docker logs boot-container-250522
```
- 8787 포트로 외부에 노출
- 환경 변수는 .env로부터 주입
- PostgreSQL과 동일 네트워크(db-network) 사용

<img width="944" alt="Image" src="https://github.com/user-attachments/assets/93ebe9af-8624-493e-8911-d97905f26ac1" />

### 3. Docker Compose로 통합 자동화
- docker-compose.yml
```yaml
services:
  # spring boot
  app:
    build: .
    ports:
      - "${APP_PORT}:8080"  # 외부 -> 내부 포트 연결
    env_file:
      - ".env"
    networks:
      - "app-network"
    depends_on:
      - postgresql  # DB 먼저 실행
  # Postgres
  postgresql:
    image: "postgres:16-alpine"
    env_file:
      - ".env"
    ports:
      - "${DB_PORT}:5432"  # 외부 -> DB 포트 연결
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - "app-network"

volumes:
  db-data:  # DB 데이터 영속화

networks:
  app-network:
```
- .env
```dotenv
DB_URL=jdbc:postgresql://postgresql:5432/postgres
DB_USERNAME=postgres
DB_PASSWORD=rootpass
# 포트
APP_PORT=18787
DB_PORT=15432
# DB
POSTGRES_PASSWORD=rootpass
```
postgresql은 서비스 이름이며 내부 네트워크의 호스트명으로 작동
```bash
docker compose up  # 실행
docker compose down  # 중지 및 정리
```

<img width="941" alt="Image" src="https://github.com/user-attachments/assets/44a21215-e7ca-4669-819b-daef7a2bd580" />
