### ISSUE TITLE
TIL -2025-05-27  []

### ISSUE THREAD

**Issue by soheeGit** [soheeGit/Programmers_AI_BackEnd#76]
### 1. application.yml 설정
```yaml
spring:
  application:
    name: boot-from-compose
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  prometheus:
    metrics:
      export:
        enabled: true
```
- /actuator/prometheus 엔드포인트를 외부에서 접근 가능하도록 설정
- Prometheus에서 메트릭 수집이 가능해짐
- 테스트 URL: http://localhost:8080/actuator/prometheus

<img width="940" alt="Image" src="https://github.com/user-attachments/assets/e8f0e761-f52d-4e67-b67f-debe874bee74" />

### 2. Prometheus 설정 (prometheus.yml)
```yaml
global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'spring-boot-app'
    static_configs:
      - targets: ['host.docker.internal:8080']
    metrics_path: '/actuator/prometheus'

# Alert Rule 등록
rule_files:
  - "alert.rules.yml"

# AlertManager 연결
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['host.docker.internal:9093']
```
- host.docker.internal 은 Docker 컨테이너가 호스트의 8080 포트로 접근하도록 설정함
- prometheus.yml, alert.rules.yml은 ./prometheus/ 폴더에 위치시킨다.

### 3. AlertManager 설정 (alertmanager.yml)
```yaml
route:
  receiver: slack

receivers:
  - name: slack
    slack_configs:
      - api_url: "<SLACK_WEBHOOK_URL>"
        text: "{{ .CommonAnnotations.summary }} - {{ .CommonAnnotations.description }}"
```
- Slack Webhook 연동을 통해 알림 전송 설정

### 4. 알림 조건 설정 (alert.rules.yml)
```yaml
groups:
  - name: give_me_money
    rules:
      - alert: give_me_money
        expr: rate(give_me_money_total[10s]) > 10
        for: 10s
        labels:
          severity: warning
        annotations:
          summary: "give_me_money"
          description: "돈 주세요"
```
- give_me_money_total이 초당 10 이상이면 경고 발송

### 5. 테스트 스크립트 (test.sh)
```Shell
#!/bin/bash

success_count=0
fail_count=0

for i in {1..10000}; do
  if (( RANDOM % 2 )); then
    curl -s http://localhost:8080/counted > /dev/null
    ((success_count++))
    echo "[${i}/10000] Success: counted endpoint (Total: ${success_count})"
  else
    curl -s http://localhost:8080/error > /dev/null
    ((fail_count++))
    echo "[${i}/10000] Failure: error endpoint (Total: ${fail_count})"
  fi
  sleep 1
done

echo "Test complete: ${success_count} successes, ${fail_count} failures."
echo "Checking Prometheus metrics..."
curl -s http://localhost:8080/actuator/prometheus | grep give_me_money_total
```
### 6. Docker 컨테이너 실행
```bash
# 기존 컨테이너 제거 (필요 시)
docker rm -f prometheus alertmanager

# Prometheus 실행
docker run -d -p 9090:9090 \
  -v ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml \
  -v ./prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml \
  --name prometheus \
  prom/prometheus:latest

# AlertManager 실행
docker run -d -p 9093:9093 \
  -v ./prometheus/alertmanager.yml:/etc/alertmanager/config.yml \
  --name alertmanager \
  prom/alertmanager:latest

sh test.sh
```
- 만약 권한 오류가 난다면 ${pwd] 대신 절대 경로를 사용해야 권한 오류가 발생하지 않는다.

### 7. 확인 포인트
항목 | 주소 또는 명령어
-- | --
Prometheus UI | http://localhost:9090
AlertManager UI | http://localhost:9093
Spring Boot Actuator | http://localhost:8080/actuator/prometheus
테스트 실행 | sh test.sh

### 예시 스크린샷

<img width="1456" alt="Image" src="https://github.com/user-attachments/assets/215e3fcf-6dfe-4edb-a120-e9c7e7cee855" />

<img width="1461" alt="Image" src="https://github.com/user-attachments/assets/0f7dc5ac-573e-40c6-9b11-b55f31b3048e" />

<img width="1466" alt="Image" src="https://github.com/user-attachments/assets/cd660d97-132d-48d6-9629-bd01d98abb4e" />

---

## 📌 오늘의 학습
⭐ 주요 학습내용1

---

## ✅ 참고 자료
